project_name: pscale
release:
  prerelease: auto # don't publish release with -rc1,-pre, etc suffixes
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/pscale/main.go
    ldflags:
     - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    binary: "pscale"   
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
nfpms:
  - maintainer: PlanetScale
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    description: The PlanetScale CLI
    homepage: https://github.com/planetscale/cli
    license: Apache 2.0
    formats:
    - deb
    - rpm
    replacements:
      darwin: macOS
brews:
  - homepage: "https://planetscale.com/"
    description: "The PlanetScale CLI"
    name: "pscale"
    license: Apache 2.0
    tap: 
      owner: planetscale
      name: homebrew-tap
    dependencies:
      - name: mysql # needed for 'pscale shell'
        type: optional
    folder: Formula
    test: |
         system "#{bin}/pscale --version"
    install: |
      bin.install "pscale"
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
